// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Global error handler for auth errors
supabase.auth.onAuthStateChange((event, session) => {
  // Handle auth errors globally
  if (event === 'TOKEN_REFRESHED' && !session) {
    // Clear any stored auth data
    localStorage.removeItem('supabase.auth.token');
    // Redirect to auth page
    if (window.location.pathname !== '/auth') {
      window.location.href = '/auth';
    }
  }
});