// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsrwyxqcsgpejxjldkba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcnd5eHFjc2dwZWp4amxka2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTY2NTAsImV4cCI6MjA3MjA3MjY1MH0.J9aDqMjq7upSCNr1QqxpM3Cecbu18ksT9SwwzjXKmi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});